common: &common
  dev_key: AI39si4pxDLC4pu4-Phm42E83mfbgb4DtiwQw7SfuSvIyKDGkV3QUOLjVLArjOfXhgXD6zKYH3N4saUEmGso3iMCVTPAAbLqQg
  username:  hongkyu
  password:  g3
  
test:
  <<: *common
development:
  <<: *common
production:
  <<: *common
