require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChSearchesController do

  # This should return the minimal set of attributes required to create a valid
  # ChSearch. As you add validations to ChSearch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChSearchesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all ch_searches as @ch_searches" do
      ch_search = ChSearch.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ch_searches).should eq([ch_search])
    end
  end

  describe "GET show" do
    it "assigns the requested ch_search as @ch_search" do
      ch_search = ChSearch.create! valid_attributes
      get :show, {:id => ch_search.to_param}, valid_session
      assigns(:ch_search).should eq(ch_search)
    end
  end

  describe "GET new" do
    it "assigns a new ch_search as @ch_search" do
      get :new, {}, valid_session
      assigns(:ch_search).should be_a_new(ChSearch)
    end
  end

  describe "GET edit" do
    it "assigns the requested ch_search as @ch_search" do
      ch_search = ChSearch.create! valid_attributes
      get :edit, {:id => ch_search.to_param}, valid_session
      assigns(:ch_search).should eq(ch_search)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChSearch" do
        expect {
          post :create, {:ch_search => valid_attributes}, valid_session
        }.to change(ChSearch, :count).by(1)
      end

      it "assigns a newly created ch_search as @ch_search" do
        post :create, {:ch_search => valid_attributes}, valid_session
        assigns(:ch_search).should be_a(ChSearch)
        assigns(:ch_search).should be_persisted
      end

      it "redirects to the created ch_search" do
        post :create, {:ch_search => valid_attributes}, valid_session
        response.should redirect_to(ChSearch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ch_search as @ch_search" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChSearch.any_instance.stub(:save).and_return(false)
        post :create, {:ch_search => {}}, valid_session
        assigns(:ch_search).should be_a_new(ChSearch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChSearch.any_instance.stub(:save).and_return(false)
        post :create, {:ch_search => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ch_search" do
        ch_search = ChSearch.create! valid_attributes
        # Assuming there are no other ch_searches in the database, this
        # specifies that the ChSearch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChSearch.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => ch_search.to_param, :ch_search => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested ch_search as @ch_search" do
        ch_search = ChSearch.create! valid_attributes
        put :update, {:id => ch_search.to_param, :ch_search => valid_attributes}, valid_session
        assigns(:ch_search).should eq(ch_search)
      end

      it "redirects to the ch_search" do
        ch_search = ChSearch.create! valid_attributes
        put :update, {:id => ch_search.to_param, :ch_search => valid_attributes}, valid_session
        response.should redirect_to(ch_search)
      end
    end

    describe "with invalid params" do
      it "assigns the ch_search as @ch_search" do
        ch_search = ChSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => ch_search.to_param, :ch_search => {}}, valid_session
        assigns(:ch_search).should eq(ch_search)
      end

      it "re-renders the 'edit' template" do
        ch_search = ChSearch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChSearch.any_instance.stub(:save).and_return(false)
        put :update, {:id => ch_search.to_param, :ch_search => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ch_search" do
      ch_search = ChSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => ch_search.to_param}, valid_session
      }.to change(ChSearch, :count).by(-1)
    end

    it "redirects to the ch_searches list" do
      ch_search = ChSearch.create! valid_attributes
      delete :destroy, {:id => ch_search.to_param}, valid_session
      response.should redirect_to(ch_searches_url)
    end
  end

end
